# Generated by Django 4.0.3 on 2023-09-18 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_dart_is_2_delete_dart_is'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dart_is_2',
        ),
    ]
