# Generated by Django 4.0.3 on 2023-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_delete_dart_is_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvTotalCompanyInfo',
            fields=[
                ('kis', models.TextField(blank=True, db_column='KIS', primary_key=True, serialize=False)),
                ('stock', models.TextField(blank=True, db_column='Stock', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('market_category', models.TextField(blank=True, db_column='Market_category', null=True)),
                ('market_category_revised', models.TextField(blank=True, db_column='Market_category_revised', null=True)),
                ('industry_code', models.TextField(blank=True, db_column='Industry_code', null=True)),
                ('industry_code_revised', models.IntegerField(blank=True, db_column='Industry_code_revised', null=True)),
                ('industry_name', models.TextField(blank=True, db_column='Industry_name', null=True)),
                ('industry_category', models.TextField(blank=True, db_column='Industry_category', null=True)),
                ('group', models.TextField(blank=True, db_column='Group', null=True)),
                ('ceo', models.TextField(blank=True, db_column='CEO', null=True)),
                ('establishment_date', models.TextField(blank=True, db_column='Establishment_date', null=True)),
                ('listing_date', models.TextField(blank=True, db_column='Listing_date', null=True)),
                ('company_size', models.TextField(blank=True, db_column='Company_size', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('website', models.TextField(blank=True, db_column='Website', null=True)),
                ('main_products', models.TextField(blank=True, db_column='Main_products', null=True)),
            ],
            options={
                'db_table': 'KV_total_company_info',
                'managed': False,
            },
        ),
    ]
